name: healthcheck
on: 
  workflow_dispatch:
  schedule:
  - cron: "21 0 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Check Next.js is returning 20x status code
        id: check-next
        # continue-on-error: true
        run: |
          # curl --silent --show-error --fail https://open-data-monitor.splitgraph.io
          curl --silent --show-error --fail https://onpaws.com/knownfailurl
      - name: Notify Mattermost if failed
        if: ${{ steps.check-next.outcome == 'failure' }}
        run: |
          curl -i -X POST --data-urlencode \
            -d '{"text": "Chinavirusssss 🤡"}' \
            $MM_OPENDATAMONITOR_ALERT_URL