name: healthcheck
on: 
  workflow_dispatch:
  schedule:
  - cron: "21 0 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Check Next.js is returning 20x status code
        id: check-next
        # continue-on-error: true
        run: |
          curl --silent --show-error --fail https://open-data-monitor.splitgraph.io
      # - name: Notify Mattermost if failed
      #   if: ${{ steps.check-next.outcome == 'failure' }}
      #   run: |
      #     curl -i -X POST -H 'Content-Type: application/json' \
      #       -d 'payload={"text": "" }' \
      #       -d '{"text": "curl req to https://open-data-monitor.splitgraph.io failed :warning:\nConsider investigating."}' \
      #       http:///mattermost.splitgraph.io/hooks/xxx-generatedkey-xxx


# TODO: assuming we want to notify MM, get an MM key from @mildbyte